import { ZUNG_JUNG_FAN_ID } from "./fan";

export enum ZUNG_JUNG_CATEGORY {
  MEN_DUAN_PIN = 1,
  QING_YI_SE = 2,
  ZI_PAI = 3,
  KE_GANG = 4,
  YI_SE_TONG_SHUN = 5,
  SAN_SE = 6,
  LIAN_XU = 7,
  YAO_JIU = 8,
  OU_RAN = 9,
  TE_SHU_HU_PAI_XING = 10,
  QI_TA = 11,
}

export const ZUNG_JUNG_CATEGORY_FAN: Record<ZUNG_JUNG_CATEGORY, ZUNG_JUNG_FAN_ID[]> = {
  [ZUNG_JUNG_CATEGORY.MEN_DUAN_PIN]: [ZUNG_JUNG_FAN_ID.PING_HU, ZUNG_JUNG_FAN_ID.MEN_QIAN_QING, ZUNG_JUNG_FAN_ID.DUAN_YUAO_JIU],
  [ZUNG_JUNG_CATEGORY.QING_YI_SE]: [ZUNG_JUNG_FAN_ID.HUN_YI_SE, ZUNG_JUNG_FAN_ID.QING_YI_SE, ZUNG_JUNG_FAN_ID.JIU_LIAN_BAO_DENG],
  [ZUNG_JUNG_CATEGORY.ZI_PAI]: [ZUNG_JUNG_FAN_ID.FAN_PAI, ZUNG_JUNG_FAN_ID.XIAO_SAN_YUAN, ZUNG_JUNG_FAN_ID.DA_SAN_YUAN, ZUNG_JUNG_FAN_ID.XIAO_SAN_FENG, ZUNG_JUNG_FAN_ID.DA_SAN_FENG, ZUNG_JUNG_FAN_ID.XIAO_SI_XI, ZUNG_JUNG_FAN_ID.DA_SI_XI, ZUNG_JUNG_FAN_ID.ZI_YI_SE],
  [ZUNG_JUNG_CATEGORY.KE_GANG]: [ZUNG_JUNG_FAN_ID.DUI_DUI_HU, ZUNG_JUNG_FAN_ID.ER_AN_KE, ZUNG_JUNG_FAN_ID.SAN_AN_KE, ZUNG_JUNG_FAN_ID.SI_AN_KE, ZUNG_JUNG_FAN_ID.YI_GANG, ZUNG_JUNG_FAN_ID.ER_GANG, ZUNG_JUNG_FAN_ID.SAN_GANG, ZUNG_JUNG_FAN_ID.SI_GANG],
  [ZUNG_JUNG_CATEGORY.YI_SE_TONG_SHUN]: [ZUNG_JUNG_FAN_ID.YI_BAN_GAO, ZUNG_JUNG_FAN_ID.LIANG_BAN_GAO, ZUNG_JUNG_FAN_ID.YI_SE_SAN_TONG_SHUN, ZUNG_JUNG_FAN_ID.YI_SE_SI_TONG_SHUN],
  [ZUNG_JUNG_CATEGORY.SAN_SE]: [ZUNG_JUNG_FAN_ID.SAN_SE_TONG_SHUN, ZUNG_JUNG_FAN_ID.SAN_SE_XIAO_TONG_KE, ZUNG_JUNG_FAN_ID.SAN_SE_TONG_KE],
  [ZUNG_JUNG_CATEGORY.LIAN_XU]: [ZUNG_JUNG_FAN_ID.YI_QI_TONG_GUAN, ZUNG_JUNG_FAN_ID.SAN_LIAN_KE, ZUNG_JUNG_FAN_ID.SI_LIAN_KE],
  [ZUNG_JUNG_CATEGORY.YAO_JIU]: [ZUNG_JUNG_FAN_ID.HUN_QUAN_DAI_YAO, ZUNG_JUNG_FAN_ID.CHUN_QUAN_DAI_YAO, ZUNG_JUNG_FAN_ID.HUN_YAO_JIU, ZUNG_JUNG_FAN_ID.QING_YAO_JIU],
  [ZUNG_JUNG_CATEGORY.OU_RAN]: [ZUNG_JUNG_FAN_ID.HAI_DI_LAO_YUE, ZUNG_JUNG_FAN_ID.HE_DI_LAO_YU, ZUNG_JUNG_FAN_ID.LING_SHANG_KAI_HUA, ZUNG_JUNG_FAN_ID.QIANG_GANG, ZUNG_JUNG_FAN_ID.TIAN_HU, ZUNG_JUNG_FAN_ID.DI_HU],
  [ZUNG_JUNG_CATEGORY.TE_SHU_HU_PAI_XING]: [ZUNG_JUNG_FAN_ID.SHI_SAN_YAO_JIU, ZUNG_JUNG_FAN_ID.QI_DUI_ZI],
  [ZUNG_JUNG_CATEGORY.QI_TA]: [ZUNG_JUNG_FAN_ID.PIAN_HUA, ZUNG_JUNG_FAN_ID.ZHENG_HUA, ZUNG_JUNG_FAN_ID.QI_SI_HUA, ZUNG_JUNG_FAN_ID.QI_SI_JI, ZUNG_JUNG_FAN_ID.JI_HU]
}